apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: voting-service-back
  name: voting-service-back
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: voting-service-back
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: voting-service-back
    spec:
      containers:
        - env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
          image: mcr.microsoft.com/oss/bitnami/redis:6.0.8
          name: voting-service-back
          ports:
            - containerPort: 6379
          resources: {}
      restartPolicy: Always
status: {}

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: voting-service-front
  name: voting-service-front
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: voting-service-front
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: voting-service-front
    spec:
      containers:
        - env:
            - name: REDIS
              value: voting-service-back
          image: ghcr.io/james-leha/demoday-aks-to-z/voting-service-front:v1
          name: voting-service-front
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}